from sqlmodel import SQLModel, Field, Relationship
from typing import Optional, TYPE_CHECKING
from datetime import datetime
from sqlalchemy import Column
from sqlalchemy.types import JSON

# Avoid circular imports for type checking
if TYPE_CHECKING:
    from app.models.camera import Camera


class Event(SQLModel, table=True):
    """
    Database model representing an event generated by a camera.

    Attributes:
        id (Optional[int]): Primary key of the event.
        camera_id (int): Foreign key linking the event to a camera.
        timestamp (datetime): Time when the event occurred.
        type (str): Type of event (e.g., "motion_detected", "person_detected").
        description (Optional[str]): Optional human-readable description.
        importance (int): Priority level (0=low, 1=normal, 2=critical).
        payload (Optional[dict]): Flexible JSON metadata (e.g., bounding boxes, scores).
        camera (Optional[Camera]): ORM relationship to the associated camera.

    Notes:
        - Indexed fields are optimized for querying (filtering/sorting).
        - JSON payload allows flexible storage of vision-related metadata.
        - Timestamp defaults to current UTC time.
    """

    # Unique identifier for the event
    id: Optional[int] = Field(default=None, primary_key=True)

    # Foreign key linking to the camera
    # Indexed for faster filtering by camera
    camera_id: int = Field(foreign_key="camera.id", index=True)

    # Timestamp of event creation
    # Indexed for efficient time-based queries (e.g., latest events)
    timestamp: datetime = Field(default_factory=datetime.utcnow, index=True)

    # Type/category of the event (e.g., motion, intrusion, object detection)
    # Indexed for filtering by event type
    type: str = Field(index=True)

    # Optional human-readable description
    description: Optional[str] = None

    # Importance level of the event
    # Indexed to support priority-based queries
    importance: int = Field(default=1, index=True)

    # Flexible JSON payload for storing additional structured data
    # Example: bounding boxes, confidence scores, labels, etc.
    payload: Optional[dict] = Field(
        default=None,
        sa_column=Column(JSON, nullable=True)
    )

    # Relationship to the Camera model
    # Enables ORM navigation (event.camera)
    camera: Optional["Camera"] = Relationship(back_populates="events")
